# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighting_function <- function(x, wf_mean, wf_sd, wf_exponent) {
    .Call(`_wsre_weighting_function`, x, wf_mean, wf_sd, wf_exponent)
}

gauss_kde <- function(x, x_samples, bandwidth) {
    .Call(`_wsre_gauss_kde`, x, x_samples, bandwidth)
}

weight_gauss_kde_jones <- function(x, weighted_samples, wf_mean, wf_sd, wf_exponent, bandwidth) {
    .Call(`_wsre_weight_gauss_kde_jones`, x, weighted_samples, wf_mean, wf_sd, wf_exponent, bandwidth)
}

weight_gauss_kde_bhatt <- function(x, weighted_samples, wf_mean, wf_sd, wf_exponent, bandwidth) {
    .Call(`_wsre_weight_gauss_kde_bhatt`, x, weighted_samples, wf_mean, wf_sd, wf_exponent, bandwidth)
}

